### ISSUE TITLE
Questionário de IHC.

### ISSUE THREAD

**Issue by libna** [libna/student-monitoring#23]

**Comment by Wolaci** [comment]
Como assim?

**Comment by ranierivalenca** [comment]
Melhorar descrição

**Comment by lilialnas** [comment]
Definir a técnica para coleta das necessidades do usuário na perspectiva de IHC.
Incluir questionários, realizar entrevistas, brainstorming ou grupo de focos.

**Comment by rebecacristina** [comment]
Link do formulário de avaliação do monitoramento estudantil.
IHC- Liliane

https://forms.gle/zPZSH94mdrkWYfc7A

**Comment by rebecacristina** [comment]
Link de avaliação do monitoramento estudantil.
IHC- liliane
https://forms.gle/wsdVprXX3TBnEpz38

**Comment by lilialnas** [comment]
Coloca o link da aplicação aqui, pois o questionário fala de alguma aplicação que já existe e eu não sei o que é. @libna @rebecacristina 
Outra coisa: este questionário está mais para uma avaliação do que uma coleta de necessidades dos usuários.
