### ISSUE TITLE
Prototipação da Tela do home

### ISSUE THREAD

**Issue by m4nunkind** [libna/student-monitoring#38]
Eu como desenvolvedor quero prototipar  a tela de login para auxiliar na construção do front-end e back-end.

**Comment by rebecacristina** [comment]
Link para os protótipos https://github.com/rebecacristina/prototipodoprojeto.git

**Comment by rebecacristina** [comment]
Tive dificuldades em entender como fazia a issue, mas pesquisei sobre bootstrap e colhi alguns protótipos para me basear.

**Comment by rebecacristina** [comment]
LInk para o protótipo do Monitoramento estudantil: https://github.com/rebecacristina/prototipo-do-projeto.git
